### PR TITLE
design: get capp's pods and containers

### PR DESCRIPTION
**Pull request by arielsepton**

### CODE REVIEW

**Comment by mzeevi** [comment]
This already exists in part here https://github.com/dana-team/platform-backend/blob/main/docs/api/containers.md. So make the needed changes to that so we can merge

**Comment by arielsepton** [comment]
@mzeevi Sure, I updated the PR. Also, should we add more generalized endpoints for retrieving pods and containers? Specifically, would endpoints like `deployments/{name}/pods` and `deployments/{name}/pods/{name}/containers` be useful?

**Comment by mzeevi** [comment]
> Specifically, would endpoints like `deployments/{name}/pods` and `deployments/{name}/pods/{name}/containers` be useful?

I don't think we need these right now

**Review by mzeevi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
