### PR TITLE
feat: implement multi cluster support

### PR DESCRIPTION
**Pull request by arielsepton**

### CODE REVIEW

**Review by fran2810 — COMMENTED** [review]
Looks good, why we keeping the TODO: of deletion of the old router group ?

**Review by fran2810 — COMMENTED** [review]
dont we need to change router tests for logs and containers ?

**Comment by arielsepton** [comment]
@fran2810 The PR is still in draft, so all TODOs will be addressed before it’s finalized.

**Comment by fran2810** [comment]
> @fran2810 The PR is still in draft, so all TODOs will be addressed before it’s finalized.

I'm sorry our boss told me to do the review, i didn't look on the pr tags  :sweat_smile:

**Comment by arielsepton** [comment]
> @arielsepton I'm sorry our boss told me to do the review, i didn't look on the pr tags  :sweat_smile: 

No problem at all! Thanks for taking the time to review it anyway. 😊

**Pull request closed without merging**
